name: run tests
on: [pull_request]


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python_version: [3.8, 3.9, 3.10.x, 3.11.x]
        java_version: [8,11]
        java_distribution: [temurin]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: ${{ matrix.java_distribution }}
          java-version: ${{ matrix.java_version }}
      - name: Setup Python ${{ matrix.python_version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python_version }}
      - name: Run maven tests
        run: mvn dependency:copy-dependencies -f java-dependencies/pom.xml
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions poetry==1.5.1
      - name: make jars dir
        run: mkdir -p src/pymeter/resources/jars
      - name: copy jars
        run: cp java-dependencies/target/dependency/* src/pymeter/resources/jars
      - name: display jars
        run: ls -l src/pymeter/resources/jars
      - name: test with tox
        run: tox
